version: "2.8"
services:
  #SERVICIO DE LA BASE DE DATOS
  database:
    build: ./database
    ports:
      - "5432:5432"
    expose:
      - "5432"
  #SERVICIO DEL PRODUCTOR
  server:
    build: ./go_server
    ports:
      - "9090:9090"
    expose:
      - "9090"
    environment:
      - DATABASE=database
      - NATS_SERVER=nats
      - NATS_SUBJECT=MicroservicesLogs
    depends_on:
      - database
      - nats
  #SERVICIO DEL CONSUMIDOR
  cliente:
    build: ./logs-manage-api
    depends_on:
      - log_database
      - nats
    environment:
      - NATS_SERVER=nats
      - DATABASE=log_database
      - DATABASE_PORT=3306
      - ROOT_PASSWORD=andres_1
      - PUERTO=9091
    ports:
      - "9091:9091"
    expose:
      - "9091"
  #SERVICIO DE NATS
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    expose:
      - "4222"
  #SERVICIO DE LA BASE DE DATOS DE LOS LOGS
  log_database:
    build: ./logs-database
    ports:
      - "3307:3306"
    expose:
      - "3306"
  #SERVICIO DE JENKINS
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "6432:8080"
      - "50000:50000"
    environment:
      - USER_SERVER_HOST=server
      - LOGS_HOST=cliente
      - LOGS_DATABASE=log_database
  #SERVICIO DE HEALTH DATABASE
  health_database:
    image: mysql:latest
    ports:
      - "3308:3306"
    expose:
      - "3308"
    environment:
      MYSQL_DATABASE: db1
      MYSQL_ROOT_PASSWORD: andres_1
  #SERVICIO DE HEALTH SERVER
  health_server:
    build: ./health_server
    ports:
      - "9092:9092"
    expose:
      - "9092"
    depends_on:
      - health_database
