global:
  scrape_interval: 15s # Intervalo de tiempo para el scraping

scrape_configs:
  - job_name: "microservices"
    static_configs:
      - targets: ["localhost:9090"]
    metrics_path: "/api/v1/health" # Nueva ruta para el scraping
