version: "2.8"
services:
  #SERVICIO DE LA BASE DE DATOS
  database:
    build: ./database
    ports:
      - "5432:5432"
    expose:
      - "5432"
  #SERVICIO DEL PRODUCTOR
  server:
    build: ./go_server
    ports:
      - "9090:9090"
    expose:
      - "9090"
    environment:
      - DATABASE=database
      - NATS_SERVER=nats
    depends_on:
      - database
  #SERVICIO DEL CONSUMIDOR
  cliente:
    build: ./logs-api
    depends_on:
      - nats
    environment:
      - NATS_SERVER=nats
  #SERVICIO DE NATS
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    expose:
      - "4222"
