version: "2.8"
services:
  # ---------------------- #
  # USER AUTH SERVICES
  # ---------------------- #

  #USER AUTH DATABASE
  database:
    build: ./auth_database
    ports:
      - "5432:5432"
    expose:
      - "5432"
  #USER AUTH SERVICE
  server:
    build: ./auth_server
    ports:
      - "9090:9090"
    expose:
      - "9090"
    environment:
      - DATABASE=database
      - NATS_SERVER=nats
      - NATS_SUBJECT=MicroservicesLogs
    depends_on:
      - database
      - nats

  # ---------------------- #
  # LOGS MANAGE SERVICES
  # ---------------------- #

  # LOGS MANAGER SERVICE
  cliente:
    build: ./logs_manager_server
    depends_on:
      - log_database
      - nats
    environment:
      - NATS_SERVER=nats
      - DATABASE=log_database
      - DATABASE_PORT=3306
      - ROOT_PASSWORD=andres_1
      - PUERTO=9091
    ports:
      - "9091:9091"
    expose:
      - "9091"

  #LOGS MANAGER DATABASE
  log_database:
    build: ./logs_manager_database
    ports:
      - "3307:3306"
    expose:
      - "3306"

  # ---------------------- #
  # HEALTH SERVICES
  # ---------------------- #

  #HEALTH SERVice
  health_server:
    build: ./health_server
    ports:
      - "9092:9092"
    expose:
      - "9092"
    depends_on:
      - health_database
    environment:
      - DB_HOST=health_database
      - NATS_SERVER=nats

  #HEALTH SERVICE DATABASE
  health_database:
    image: mysql:latest
    ports:
      - "3308:3306"
    expose:
      - "3308"
    environment:
      MYSQL_DATABASE: applications
      MYSQL_ROOT_PASSWORD: andres_1

  # ---------------------- #
  # USER PROFILE SERVICES
  # ---------------------- #

  #USER PROFILE SERVICE
  user_profile:
    build: ./user_profile_server
    ports:
      - "9094:9094"
    expose:
      - "9094"
    depends_on:
      - nats
      - user_profile_database
    environment:
      - DATABASE=user_profile_database
      - NATS_SERVER=nats
      - NATS_SUBJECT=MicroservicesLogs

  #USER PROFILE DATABASE
  user_profile_database:
    image: mysql:latest
    ports:
      - "3309:3306"
    expose:
      - "3309"
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: andres_1

  # ---------------------- #
  # NOTIFICATION SERVICES
  # ---------------------- #

  #NOTIFICATION SERVICE
  notification_server:
    build: ./notification_server
    ports:
      - "9096:9096"
    expose:
      - "9096"
    depends_on:
      - nats
      - notification_database
    environment:
      - DB_NOTIFICATION_HOST=notification_database
      - NATS_SERVER=nats
      - NATS_SUBJECT=MicroservicesLogs

  #NOTIFICATION DATABASE
  notification_database:
    image: mysql:latest
    ports:
      - "3310:3306"
    expose:
      - "3310"
    environment:
      MYSQL_DATABASE: notifications
      MYSQL_ROOT_PASSWORD: andres_1

  # ---------------------- #
  # GATEWAY SERVICES
  # ---------------------- #

  #GATEWAY SERVICE
  gateway_server:
    build: ./gateway_server
    ports:
      - "9095:9095"
    expose:
      - "9095"
    depends_on:
      - nats
      - user_profile
      - notification_server
      - server
      - cliente
      - health_server
    environment:
      - USER_SERVER_HOST=server
      - LOGS_HOST=cliente
      - HEALTH_HOST=health_server
      - USER_PROFILE_HOST=user_profile
      - NOTIFICATION_HOST=notification_server
      - NATS_SERVER=nats

  # ---------------------- #
  # AUXILIAR SERVICES
  # ---------------------- #

  #NATS SERVICE
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    expose:
      - "4222"

  #JENKINS SERVICE
  jenkins:
    build: ./jenkins_configuration
    ports:
      - "6432:8080"
      - "50000:50000"
    environment:
      - USER_SERVER_HOST=server
      - LOGS_HOST=cliente
      - LOGS_DATABASE=log_database
      - HEALTH_HOST=health_server
      - USER_PROFILE_HOST=user_profile
      - NOTIFICATION_HOST=notification_server

  # ---------------------- #
  # PROMETHEUS SERVICES
  # ---------------------- #

  #PROMETHEUS SERVICE
  # prometheus:
  #   image: prom/prometheus:latest # Usa la imagen oficial de Prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml # Monta el archivo de configuración
  #   ports:
  #     - "9093:9090" # Puerto para acceder a la interfaz de Prometheus
